server:
  port: 8080
#    servlet:
#        context-path: /

#mybatis:
#  config-location: classpath:mybatis.cfg.xml
#  type-aliases-package: com.huawei.devcloud.entity
#  mapper-locations:
#      - classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exhibition?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: ".Kjkttt114514"
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql, classpath:db/city.sql
      mode: always
  mvc: static-path-pattern= /**
  mail:
    username: ServerEmail_One@163.com
    password: VGSUYCDDOILEOAYO
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.exhibition.entity
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
