server:
  port: 8080
#    servlet:
#        context-path: /

mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.huawei.devcloud.entity
  mapper-locations:
      - classpath:mapper/*.xml
spring:
  datasource :
    url: jdbc:mysql://localhost:3306/exhibition?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: "000000"
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
      db-config:
          id-type: auto
          field-strategy: NOT_EMPTY
          db-type: MYSQL
  configuration:
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImp

