server:
  port: 8080
#    servlet:
#        context-path: /

#mybatis:
#  config-location: classpath:mybatis.cfg.xml
#  type-aliases-package: com.huawei.devcloud.entity
#  mapper-locations:
#      - classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exhibition?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: "woshiliuxin!2001"
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.exhibition.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
